export const transactionTitle = [
  "Debit from One-time Utilities",
  "Debit for One-time Payment",
  "Deposit of Refund Service",
  "Deposit for the Annual Fee",
  "Deposit from Recurring Subscription",
  "Debit to Quarterly Subscription",
  "Deposit of Monthly Rent",
  "Transfer of Refund Service",
  "Debit on Recurring Subscription",
  "Deposit at Credit Fee",
  "Refund at One-time Rent",
  "Debit on Debit Utilities",
  "Invoice of Annual Subscription",
  "Deposit for the Quarterly Payment",
  "Payment for the One-time Account",
  "Withdrawal for the Credit Payment",
  "Credit for Recurring Utilities",
  "Payment for Refund Payment",
  "Withdrawal to Debit Payment",
  "Invoice for the Recurring Utilities",
  "Deposit for the One-time Invoice",
  "Debit from One-time Invoice",
  "Refund to Monthly Utilities",
  "Debit from Quarterly Utilities",
  "Transfer to Credit Utilities",
  "Transfer from Annual Rent",
  "Debit to Credit Payment",
  "Deposit for the Recurring Rent",
  "Refund for the Quarterly Subscription",
  "Debit on Quarterly Utilities",
  "Debit for the Monthly Subscription",
  "Deposit on Quarterly Rent",
  "Credit of Credit Rent",
  "Debit for the Recurring Service",
  "Invoice for Monthly Invoice",
  "Credit for the Debit Fee",
  "Credit from Annual Rent",
  "Payment on One-time Utilities",
  "Invoice from Debit Utilities",
  "Refund to Credit Utilities",
  "Credit for Debit Rent",
  "Invoice from Debit Utilities",
  "Refund to Monthly Utilities",
  "Invoice to Recurring Fee",
  "Debit for Monthly Invoice",
  "Transfer from Debit Utilities",
  "Invoice for the Credit Fee",
  "Debit at Refund Account",
  "Credit of Refund Rent",
  "Transfer of Debit Fee",
  "Payment at Debit Account",
  "Refund from Monthly Payment",
  "Payment at Annual Rent",
  "Debit for the Annual Fee",
  "Deposit of Quarterly Rent",
  "Payment of One-time Account",
  "Withdrawal from One-time Fee",
  "Credit from Recurring Utilities",
  "Debit from Recurring Utilities",
  "Invoice for the Credit Rent",
  "Refund of Refund Service",
  "Refund for the Quarterly Payment",
  "Transfer to Recurring Payment",
  "Transfer for the Quarterly Service",
  "Withdrawal from Recurring Account",
  "Credit from Credit Account",
  "Debit on Refund Payment",
  "Transfer for the Annual Invoice",
  "Withdrawal at Credit Invoice",
  "Payment to Debit Fee",
  "Transfer for Monthly Payment",
  "Invoice for One-time Utilities",
  "Payment from Debit Subscription",
  "Credit to Recurring Utilities",
  "Withdrawal to Recurring Service",
  "Payment from Debit Fee",
  "Withdrawal at Recurring Fee",
  "Debit on Refund Service",
  "Withdrawal for the Debit Payment",
  "Payment for the One-time Fee",
  "Transfer of Annual Subscription",
  "Debit at One-time Utilities",
  "Transfer at Monthly Fee",
  "Credit of Credit Fee",
  "Debit on Refund Subscription",
  "Refund from Monthly Account",
  "Refund for the One-time Service",
  "Refund from Monthly Rent",
  "Refund for the Refund Fee",
  "Payment to Recurring Subscription",
  "Debit at Monthly Account",
  "Withdrawal for the Debit Account",
  "Refund on Quarterly Account",
  "Deposit on Quarterly Rent",
  "Transfer at Monthly Rent",
  "Payment for Credit Account",
  "Credit for Refund Rent",
  "Refund for Monthly Fee",
  "Invoice for the Credit Subscription",
  "Payment for the Refund Service",
];
